import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/modules/common/styles/global.scss";
import NavigationModal from "@/modules/common/components/navigation/navigationModal";
import PageTransitionAnimation from "@/modules/common/components/animations/pageTransitionAnimation/Animation";

const poppins = Poppins({
	subsets: ["latin"],
	weight: ["100", "200", "400", "500", "700"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={poppins.className}>
				<NavigationModal />
				<PageTransitionAnimation />
				{children}
			</body>
		</html>
	);
}
